### ISSUE TITLE
Timeout using DHT22 with ESP_IDF on ESP32 

### ISSUE THREAD

**Issue by asweeney99** [RobTillaart/Arduino#104]
I've been testing DHTstable 0.2.4 on a DHT22 with an ESP32 dev board using arduino-esp32. It works great.

I then decided to try and port your library to the  the esp-idf framework as I needed to use it with a stable esp-idf AWS iOT library. Unfortunately, I'm getting only timeout errors when reading. Following your advice in another thread I've tried some different things: 

1K, 2.2K, 3.3K and 10K resistors
Pins 4 and 14.
2m and 1m usb cables 
5V Power supplies from usb port on PC and from mains DC converter
5V lead from board to DHT22 instead of 3.3V
3 second and 10 second delays between reads
 
No other hardware is connected. I have a second unit with identical setup which also fails. My code is in the following link:

https://drive.google.com/file/d/193NFtxayD1mRf5ayVkzf59rOd1oWVASN/view?usp=sharing

This would seem to point to a problem either in my code or in the esp-idf framework and not necessarily in DHTstable. Any comments welcome.

**Comment by RobTillaart** [comment]
There have been other timeout issues with DHT and ESP. Currently the implementation of the timeout param is calculated with 
``` C++
const int DHTLIB_TIMEOUT = (F_CPU/40000);
```

To better support "faster" platforms I was thinking to update the timeout codes with calls to micros() to have a better timeout behavior. 
```C++
start = micros();
while (digitalRead(dataPin, LOW) 
{
  if (micros() - start > 100) return TIMEOUT;
}
```
drawback on the UNO@16MHz platform was that the micros() call itself has a granularity of 4 and takes 
a few micros() to execute. For lower clockspeeds e.g. @8MHz calls to micros() take more time, too much to follow the protocoll. in a stable way. 
That said adding micros() as described above might work well on ESP.

If you want to port my DHT code to the esp-idf framework, please have a look at the DHTNEW version, which is my main branch now. It has some extra features that are usefull on ESP too.

**Comment by RobTillaart** [comment]
So issue can be closed ?
