### ISSUE TITLE
Wrong conversion to lux of Max44009 @0.1.8

### ISSUE THREAD

**Issue by vandecook** [RobTillaart/Arduino#108]
Using Version 0.1.8 for MAX44009 I got to high lux  values.

Checking the function for Max44009::getLux I found out that on 

`Line 42: uint32_t m = (dhi << 4) + (dlo & 0x0F); `
shifts the dhi value but does not mask out the upper 4 bit (exponent)

Change to 
`uint32_t m = ((dhi & 0x0F) << 4) + (dlo & 0x0F);`
will solve this issue. 

Roland

**Comment by RobTillaart** [comment]
you're right, the bug sneaked into the code in the 0.1.8 version. Ficed and version updated to 0.1.9
