### ISSUE TITLE
Temperature Compensation MS5611

### ISSUE THREAD

**Issue by flauth** [RobTillaart/Arduino#109]
in MS5611.cpp
line 96
line 103

possibly wrong conditions , instead of `if(_temperature < 20)` and `if(_temperature < -15)` should be `if(_temperature < 2000)` and `if(_temperature < -1500)`

**Comment by RobTillaart** [comment]
That lib was written quite some time ago, need to reread datasheet to check the math. 
Can take a few days before I have time.

**Comment by RobTillaart** [comment]
Quick check states indeed "TEMP Actual temperature (-40…85°C with **0.01°C** resolution)"
I'll make the fix today.

**Comment by RobTillaart** [comment]
fix pushed, Can you please verify, and if needed reopen issue?

**Comment by flauth** [comment]
fixed! thanks!

**Comment by RobTillaart** [comment]
What platform did you use to confirm it? Arduino UNO? or something else?

**Comment by flauth** [comment]
I´am using 
- Arduino MKR1000
- ESP8266 (NodeMCU)
- ESP32 (WemosLite)
all pogrammed using Arduino IDE.
`_temperature` was giving temperature in #### format.
Turned out, that your library is not working with WiFi.h Library on ESP32 ("error read 2" after a few loops). Could not figure out why, so I changed to another library.

**Comment by RobTillaart** [comment]
The wifi library is probably interrupt driven and that could disturb the I2C reading. Seen that before.
Which lib do you use now?

**Comment by flauth** [comment]
https://github.com/gronat/MS5611

i changed some things (added 2. order temperature-compensation), but nothing concerning the I2C readings...

**Comment by RobTillaart** [comment]
thx
