### ISSUE TITLE
Wrong temperature reading of AM2322

### ISSUE THREAD

**Issue by 9a4gl** [RobTillaart/Arduino#114]
In `Arduino/libraries/AM232X/AM232X.cpp`
`int AM232X::read()`

`temperature = (bits[4] & 0x7F)*256 + bits[5] * 0.1;`

should be

`temperature = ((bits[4] & 0x7F)*256 + bits[5]) * 0.1;`

BR,
Tihomir

**Comment by 9a4gl** [comment]
Looks you increased a version, but you forgot to add a fix.

**Comment by RobTillaart** [comment]
I started to isolate all sensors in their own repo, this one too https://github.com/RobTillaart/AM232X
That said I will update this lib in the bulk repo as the bug is serious above 25.6C

Thanks for pointing out.

**Comment by RobTillaart** [comment]
Solved, sorry for the inconvenience.
