### ISSUE TITLE
Negative Temperatures do not work

### ISSUE THREAD

**Issue by baderas** [RobTillaart/Arduino#120]
I can't give any technical details, but with your libarary temperatures below 0°C do not work. They report as e.g. -3277.70 not -1.0. 
Changed back to adafruits library -> everything works fine with my DHT22.
Therefore I think you library does not convert the negative temperatures correctly.

**Comment by yesyesuk** [comment]
Are you sure you are using the latest version? This is something that has been fixed years ago.

**Comment by baderas** [comment]
It happened on DHTNEW with Commit 0c4ee966da8e0f5281148e65432ca275eae96448

**Comment by baderas** [comment]
You fixed it a few month ago on DHTlib
Which one of your DHT libraries should I use on ESP8266 and DHT22?

**Comment by RobTillaart** [comment]
DHTlib should work, do not forget to use a 3.3 volts to 5.0 volts convertor as the DHT sensor functions more reliable at 5.0 volts. 3.3 volts is at the edge of its working range.

I indeed need to add this same fix to DHTNEW. Will look at it a.s.a.p.

**Comment by RobTillaart** [comment]
The problem is that the negative bit is not masked, causing an offset of (128*256)/10 = 3276
This matches your observation.
Fix is underway.

**Comment by RobTillaart** [comment]
Fix delivered, if the problem still occurs please reopen,
Thanks for posting the issue!
