### ISSUE TITLE
I2C_eeprom::_pageBlock overloaded "rv" var

### ISSUE THREAD

**Issue by wothke** [RobTillaart/Arduino#121]
this is really cosmetic but it seems unnecessary to create another rv variable within the loop..

**Comment by RobTillaart** [comment]
I had a quick look (did not touch those files for years) and indeed that looks stupid, and in fact the outer one (line 202) can only return 0 as it is never assigned another value.
Although the compiler will optimize this, I will fix is asap.

Thanks for pointing this out,

**Comment by RobTillaart** [comment]
fixed
