### ISSUE TITLE
I2C_EEPROM help

### ISSUE THREAD

**Issue by wothke** [RobTillaart/Arduino#122]
This is not a bug report...

but I still have a problem in my project that may or may not be related to the I2C_EEPROM library.. see http://forum.arduino.cc/index.php?topic=595064.0 

in case you have some idea might help me ..

**Comment by RobTillaart** [comment]
I've seen some problems with (I2C) devices not working correctly on 3.3V (ESP I2C voltage). For some that voltage is within specs but too close to the edge. A 3.3V - 5V bidirectional convertor on the I2C lines might fix it.

**Comment by wothke** [comment]
that's an idea, though the 24LC256 EEPROM is rated for a voltage range of 2.5-5.5V.. and 3v3 would not seem t to be anywhere close to the boundary..
