### ISSUE TITLE
RunningAverage library installation

### ISSUE THREAD

**Issue by matpi** [RobTillaart/Arduino#130]
Hi Rob,
I have a trouble with installation of RunningAverage library... it's easy for me to to this kind of stuff if there is an option "Clone or download" in GitHub, so I can just to download the .zip file, extract it and then carry the files and examples to Arduino libraries folder. I can't do this if there is not this kind of option in GitHub. Is it possible for you to make this option to download RunningAverage library? Thanks and best regards...

**Comment by RobTillaart** [comment]
I have all my libs in one repository (historical mistake perhaps :),  so you could download all of them at once and extract just the one you need from the zip.

download button - https://github.com/RobTillaart/Arduino   (right side)

**Comment by matpi** [comment]
Thank you very much! I have got it now :)
