### ISSUE TITLE
dht.lib 0.1.18  dht.cpp DHT11 Wrap around at 64 RH

### ISSUE THREAD

**Issue by RiXOR** [RobTillaart/Arduino#14]
DHT11 wraps around at 64 % RH to 0 % because bit 6 is masked.
Line 50 should read  bits[0] &= 0x7F;  instead of bits[0] &= 0x3F;

Tested with arduino mega 2560 and DHT11 (in parallel with DHT22 and HYT939) and works.

Richard

**Comment by RobTillaart** [comment]
I had seen that one too but was not on top of todo. 
anyway it is fixed version 0.1.19
