### ISSUE TITLE
download

### ISSUE THREAD

**Issue by alexbaekeland** [RobTillaart/Arduino#147]
how do I download it? I'am folowing a tutorial of How to Mechatronics. I just don't know how to download this one please help.

**Comment by RobTillaart** [comment]
Can you give a link to that description?

**Comment by RobTillaart** [comment]
- select the tab code
- go to the right under the red line
- click the green download button
- click the download ZIP button
   ==> the archive is downloaded to your computer

unzip the file and move the libraries needed to your libraries folder 
(see the Arduino IDE -> FILE menu -> PREFERENCES -> sketchbbok location

use sketchbookfolder/libraries to store your own libs.

**Comment by alexbaekeland** [comment]
Dear Rob

Thank you so mucht for replying .

Alex

Op zo 5 apr. 2020 16:47 schreef Rob Tillaart <notifications@github.com>:

**Comment by RobTillaart** [comment]
I assume I can close the issue?

**Comment by alexbaekeland** [comment]
Dear Rob

Yes you may close the case, thank you for your help.

Kind regards .
Alex

Op ma 6 apr. 2020 13:03 schreef Rob Tillaart <notifications@github.com>:
