### ISSUE TITLE
Minor oops. Error code has a duplicate case.

### ISSUE THREAD

**Issue by motivation64** [RobTillaart/Arduino#15]
Error code accidentally duplicated the connect error. I think it's fine in all of the other examples. Found this because I'm just starting to play with Arduino and this sensor. Thank you so much for this library :)

    case DHTLIB_ERROR_CONNECT:       // (Should be DHTLIB_ERROR_TIMEOUT)
        Serial.print("Time out error,\t");
        break;
    case DHTLIB_ERROR_CONNECT:
        Serial.print("Connect error,\t");
        break;

**Comment by RobTillaart** [comment]
Thanks, was copy/paste error in DHT21_test.ino example  -> fixed
