### ISSUE TITLE
Decimal point position bug

### ISSUE THREAD

**Issue by mariusl** [RobTillaart/Arduino#160]
Hi
The method used to calculate the position of the decimal point in the displayFloat function causes an error.

`int w = round(f);
  if (w > 9) pt = 1;
  if (w > 99) pt = 2;
  if (w > 999) pt = 3;`
The round function will cause the point to shift if the remainder is larger than 0.5.
This method works better.

` 
  int w = f;
  if (w < 1000) pt = 2;
  if (w < 100) pt = 1;
  if (w < 10) pt = 0;`

**Comment by RobTillaart** [comment]
Which library?

**Comment by mariusl** [comment]
So sorry, The HT16K33.

**Comment by RobTillaart** [comment]
Thanks Marius,
I see the point, please note a new version of the lib is available here https://github.com/RobTillaart/HT16K33
and it has the same flaw. 
Need to write a test.ino that shows the problem now and not anymore after the fix
Lets see if I have HW around  - expect fix will be done tomorrow.

**Comment by RobTillaart** [comment]
Test sketch, fails from  9.50  to  9.99

```cpp
//
//    FILE: test_printfloat.ino
//  AUTHOR: Rob Tillaart
// VERSION: 0.0.1
// PURPOSE: test decimal point for floats.
//     URL: http://www.adafruit.com/products/1002
//     URL: https://github.com/RobTillaart/HT16K33

#include "HT16K33.h"

HT16K33 seg(0x70);

void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);

  seg.begin();
  Wire.setClock(100000);

  seg.displayOn();
}

void loop()
{
  test_printfloat();
  Serial.println("---------------");
  delay(1000);
}

void test_printfloat()
{
  for (int i = 940; i < 1010; i++)
  {
    float f = i * 0.01;
    seg.displayFloat(f);
    delay(100);
  }
}

// -- END OF FILE --
```

**Comment by RobTillaart** [comment]
@mariusl 
I have no HW around, can you verify this version of printFloat? 
it also initialize **int pt = 3;**
```cpp
void HT16K33::displayFloat(float f)
{
  // int pt = 0;
  // uint8_t neg = 0;
  // if (f < 0) { neg = -1; f = -f; }
  if (f > 9999 || f < 0 ) return;
  int w = f; 
  int pt = 3;
  if (w < 1000) pt = 2; 
  if (w < 100) pt = 1; 
  if (w < 10) pt = 0;
  // int w = round(f);
  // if (w > 9) pt = 1;
  // if (w > 99) pt = 2;
  // if (w > 999) pt = 3;
  
  if (f >= 1)
  {
    while (f < 1000) f *= 10;
    w = round(f);
  }
  else
  {
    w = round(f * 1000);
  }

  uint8_t x[4], h, l;
  h = w / 100;
  l = w - h * 100;
  x[0] = h / 10;
  x[1] = h - x[0] * 10;
  x[2] = l / 10;
  x[3] = l - x[2] * 10;
  display(x, pt);
}
```

**Comment by mariusl** [comment]
Rob that works just fine.

**Comment by RobTillaart** [comment]
Will make a pull request tomorrow

**Comment by mariusl** [comment]
Thanks for the prompt response.

**Comment by RobTillaart** [comment]
fix delivered
