### ISSUE TITLE
displayDate

### ISSUE THREAD

**Issue by bepitama** [RobTillaart/Arduino#162]
Wanting to create a watch that also visualizes the date, I added the displayDate function that displays the date as dd.mm. You can add it to the official library. Thank you so much. Joseph

void HT16K33::displayDate(uint8_t left, uint8_t right)
{
  uint8_t x[4];
  x[0] = left / 10;
  x[1] = left - x[0] * 10;
  x[2] = right / 10;
  x[3] = right - x[2] * 10;
  display(x, 1);
  displayColon(false);
}

**Comment by RobTillaart** [comment]
Added to the latest version here - https://github.com/RobTillaart/HT16K33/releases/tag/0.2.2
