### ISSUE TITLE
Using two sensors

### ISSUE THREAD

**Issue by airestoni** [RobTillaart/Arduino#164]
Hi robtillaart,
what an amazing programming you did!
Than you for publishing it here.
I'm doing a project where i'm using two sensors and i would like to apply the running average to both of them.
Can you explain me how can I do this?

**Comment by RobTillaart** [comment]
@airestoni
Please open an issue here - https://github.com/RobTillaart/RunningAverage
as that is the repo specific for running average questions.

**Comment by RobTillaart** [comment]
prepared an example there in develop branch
