### ISSUE TITLE
Question about work

### ISSUE THREAD

**Issue by Manhem** [RobTillaart/Arduino#173]
Hi again.
Have you ever been working with TCA9555?
I have found a library but I think the are a problem.
Have you time to check it for me??

**Comment by RobTillaart** [comment]
Not so much time, but can you send a link to the library and the datasheet and a short description of the problem.

Might be an interesting challenge 🙂

**Comment by RobTillaart** [comment]
@Manhem  
- https://www.ti.com/product/TCA9555
doen't look too difficult

**Comment by RobTillaart** [comment]
Create a placeholder for a new library here -https://github.com/RobTillaart/TCA9555
