### ISSUE TITLE
 ESP8266 

### ISSUE THREAD

**Issue by BlackCipher11th** [RobTillaart/Arduino#180]
It does not compile for ESP8266 too.
I am using ESP8266 ESPresso Lite 1.0 and it does not complie for that too .

**Comment by RobTillaart** [comment]
@BlackCipher11th 
Please open an issue for the library in its own repro as this is a bulk library with no active development. 
The development and issue solving is in those separate repros. 

Note that not all libraries are tested / verified for ESP8266.

**Comment by RobTillaart** [comment]
@BlackCipher11th 
Please open an issue for the library in its own repro. I close the issue here.
