### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by lbussy** [RobTillaart/Arduino#183]
This is not an issue, so go ahead and close - I just didn't know another way to send you a note:

THANK YOU for maintaining this and the separate libs.  I know FOSS is a grind sometimes, but thank you for making these available.

**Comment by RobTillaart** [comment]
Thanks, you're welcome!

When doing projects I often encapsulate the hardware used in "half a lib". When time permits I try to make them "more or less functional complete" by going beyond my own requirements, and release them on github. And then issues come... 😁

There are more reasons to develop a lib but above all it is fun.

**Comment by RobTillaart** [comment]
btw hanks for the support!
