### ISSUE TITLE
error: cannot convert 'volatile uint32_t* to 'volatile uint8_t*

### ISSUE THREAD

**Issue by fullaware** [RobTillaart/Arduino#23]
Arduino: 1.6.5 (Mac OS X), Board: "Adafruit HUZZAH ESP8266, 80 MHz, 115200"

Build options changed, rebuilding all
Using library DHTlib in folder: /Users/fullaware/Documents/Arduino/libraries/DHTlib (legacy)

/Users/fullaware/Library/Arduino15/packages/esp8266/tools/esptool/0.4.2-winfix/xtensa-lx106-elf/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -I/Users/fullaware/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.2/sdk/include -c -Os -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -std=c++11 -MMD -DF_CPU=80000000L -DARDUINO=10605 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DESP8266 -I/Users/fullaware/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.2/cores/esp8266 -I/Users/fullaware/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.2/variants/generic -I/Users/fullaware/Documents/Arduino/libraries/DHTlib /var/folders/q_/zxstk0zn1rj1_8zx4bwkswx40000gn/T/build5382613773702674847.tmp/dht22_testbn.cpp -o /var/folders/q_/zxstk0zn1rj1_8zx4bwkswx40000gn/T/build5382613773702674847.tmp/dht22_testbn.cpp.o 
/Users/fullaware/Library/Arduino15/packages/esp8266/tools/esptool/0.4.2-winfix/xtensa-lx106-elf/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -I/Users/fullaware/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.2/sdk/include -c -Os -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -std=c++11 -MMD -DF_CPU=80000000L -DARDUINO=10605 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DESP8266 -I/Users/fullaware/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.2/cores/esp8266 -I/Users/fullaware/Library/Arduino15/packages/esp8266/hardware/esp8266/1.6.2/variants/generic -I/Users/fullaware/Documents/Arduino/libraries/DHTlib -I/Users/fullaware/Documents/Arduino/libraries/DHTlib/utility /Users/fullaware/Documents/Arduino/libraries/DHTlib/dht.cpp -o /var/folders/q_/zxstk0zn1rj1_8zx4bwkswx40000gn/T/build5382613773702674847.tmp/DHTlib/dht.cpp.o 
/Users/fullaware/Documents/Arduino/libraries/DHTlib/dht.cpp: In member function 'int8_t dht::_readSensor(uint8_t, uint8_t, uint8_t)':
/Users/fullaware/Documents/Arduino/libraries/DHTlib/dht.cpp:122:51: error: cannot convert 'volatile uint32_t* {aka volatile unsigned int*}' to 'volatile uint8_t* {aka volatile unsigned char*}' in initialization
     volatile uint8_t *PIR = portInputRegister(port);
                                                   ^
Error compiling.

**Comment by RobTillaart** [comment]
Please use the version 0.1.13, that is the version that is compatible. Later versions are AVR optimized. 

You can get the latest stable version here - https://github.com/RobTillaart/Arduino/tree/master/libraries/DHTstable 

give it a try
