### ISSUE TITLE
Running test .ino files

### ISSUE THREAD

**Issue by scheung38** [RobTillaart/Arduino#26]
Not sure why after cloning project and for example, within Ardiuno IDE 1.6.5, launching dht_test1.ino:

verify:
```
dht_test1.ino:11:17: fatal error: dht.h: No such file or directory
compilation terminated.
Error compiling.
```
Is the dht.h not already there as I did a git clone? Also could you let me know how to install it as I have previously already installed under: 
```
/Users/seb/Documents/Arduino
```
and then

libraries
hardware

directories previously installed, so relative to these where to place your set of Arduino directories.

**Comment by RobTillaart** [comment]
I do not know for IDE1.6.5 (I'm still at 1.5.8) 

In the IDE -> File menu-> preferences you can find your sketchbook path.
In that path you need to make a folder libraries (or it exists already)

create a folder dht under libraries 
so for you the path should become:  /Users/seb/Documents/Arduino/Libraries/dht

copy dht.h dht.cpp and the example folder there

restart all instances of the IDE 

and then it should work.

**Comment by RobTillaart** [comment]
As there are no further remarks I close the issue

**Comment by andrew-raphael-lukasik** [comment]
(Arduino IDE 1.6.9 and .h .cpp and .ino in the same folder)
Changing 
#include <dht.h>
to:
#include "dht.h"
fixed this issue in my case
