### ISSUE TITLE
Lastest version always return "Connect error"

### ISSUE THREAD

**Issue by h2dvnnet** [RobTillaart/Arduino#29]
Arduino Uno R3 and DHT11, version 0.1.21 always return DHTLIB_ERROR_CONNECT, but version 0.1.14 still working.

**Comment by RobTillaart** [comment]
Please use the DHTStable branch as that is the most robust version (0.1.13) 
after 0.1.13 I made several optimizations specific for AVR platform thereby breaking portability.
