### ISSUE TITLE
Truncated Tag Issue?

### ISSUE THREAD

**Issue by TravisH84** [RobTillaart/Arduino#36]
Hi Rob,

Another issue, when I call a tag for example Camera Orientation and output to the serial port I am noticing that it appears to be truncating the text and cutting it off early?

`
<cameraOrientation>landscape</cameraOrientati>
      <stabilizationDelay>250</stabilizationDe>
`

**Comment by RobTillaart** [comment]
increase the XMLWRITER_MAXTAGSIZE  in the XMLwriter.h 
e.g. 
#define XMLWRITER_MAXTAGSIZE 30

default it is set to 15 which is a balance between readability and memory usage
