### ISSUE TITLE
how to read multiple DHT11?

### ISSUE THREAD

**Issue by tofrnr** [RobTillaart/Arduino#67]
hello,
how to read multiple DHT11?
just by 
dht DHT;
and then read different DHT_pins by the same DHT one by one, e.g.
int chk = DHT.read11(6);
...
int chk = DHT.read11(7);
...
int chk = DHT.read11(8);
...

or instead create multilple dht objects with a proprietary DHT_pin each?

dht DHT1, DHT2, DHT3;
#define pinDHT1  6
#define pinDHT2  7
#define pinDHT3  8

int chk = DHT1.read11(pinDHT1);
...
int chk = DHT2.read11(pinDHT2);
...
int chk = DHT3.read11(pinDHT3);
...

?

**Comment by RobTillaart** [comment]
These questions are better asked on the Arduino, and yes you were close,
Try this
```
dht DHT;
#define pinDHT1 6
#define pinDHT2 7
#define pinDHT3 8

int chk = DHT.read11(pinDHT1);
...
int chk = DHT.read11(pinDHT2);
...
int chk = DHT.read11(pinDHT3);
```
