### ISSUE TITLE
PCF8574 input/output

### ISSUE THREAD

**Issue by ramarro123** [RobTillaart/Arduino#68]
Hi,

the PCF8574 library miss the option to set input/output per pin.

i have 3 pins that need to be setup as input and other that are output but it doesn't seems possible with the current library implementation, it's that correct?

**Comment by RobTillaart** [comment]
No, the PCF8574 does not need to be set up as input or output explicitly as there is no data-direction control register. From the datasheet page 1

*The device features an 8-bit quasi-bidirectional I/O port (P0–P7), including latched outputs with high-current drive capability for directly driving LEDs. Each quasi-bidirectional I/O can be used as an input or output* ***without the use of a data-direction control signal.***

***At power on, the I/Os are high***.  *In this mode, only a current source to VCC is active. An additional strong pullup to VCC allows fast rising edges into heavily loaded outputs. This device turns on when an output is written high and is switched off by the negative edge of SCL.* ***The I/Os should be high before being used as inputs***

So alternating a single pin between input an output might be a bit more difficult (never tried in fact)
