### ISSUE TITLE
Arduino complaining about #include "Cozir.h" in cozir.cpp

### ISSUE THREAD

**Issue by Plantgrower** [RobTillaart/Arduino#69]
My program gave an error "Cozir.h" not found when compiling. I changed the declaration #include "Cozir.h" in cozir.cpp to #include "cozir.h" and then it would compile.

**Comment by RobTillaart** [comment]
The example sketch also shows lower case #include <cozir.h> so I think it is no real problem.
but thanks for the feedback.
