### ISSUE TITLE
Invalid version found: 0.1.05

### ISSUE THREAD

**Issue by Plantgrower** [RobTillaart/Arduino#70]
When compiling the cozir library I got the warning "Invalid version found: 0.1.05" I changed  the version in the library .properties file to 0.1.5 and the warning disappeared. 0.1.05 is an invalid version number (has this changed in Arduino ?).

**Comment by RobTillaart** [comment]
I know this error exists and I need to update the properties files as you propose. Will add it to my todo list.

**Comment by RobTillaart** [comment]
Thanks per1234 for fixing, I will merge it right away
