### ISSUE TITLE
choose between I2C lines?

### ISSUE THREAD

**Issue by pwspania** [RobTillaart/Arduino#73]
Is there a way to specify which I2C to use? wire1 for example on a due?

**Comment by RobTillaart** [comment]
Some libraries do others don't.  Most of mine don't.
Which library are you referring to?

**Comment by waspinator** [comment]
I'm trying to use your MCP4725 dac library.

**Comment by waspinator** [comment]
Hmm I tried that, there must be something more to it. Works fine on the first I2C, but not on the second. I had to remove references to `TWBR`, but I'm not sure if that is related, as it still works on the first port.

**Comment by RobTillaart** [comment]
TWBR is AVR specific I guess, there is a call something like Wire.setClock(bitrate)
Have no due installed, maybe it is called differently, (I picked Wire1 from Teensy which is also ARM based)

**Comment by RobTillaart** [comment]
Updated  https://github.com/RobTillaart/Arduino/tree/master/sketches/MultiSpeedI2CScanner  to support Wire1 and Wire2 for the Teensy3.5 as I could test that one. Might give some insights.

I did not find time yet to install the due board to see how wire1 is implemented (conditionally or not)

**Comment by waspinator** [comment]
looks like it should be `Wire1` for the Due, but it wasn't working for me. I might be over looking something though.

https://github.com/arduino/ArduinoCore-sam/blob/master/libraries/Wire/src/Wire.h

**Comment by RobTillaart** [comment]
Wire1 for the Due is only defined if  WIRE_INTERFACES_COUNT > 1, 
but it is set in variants/arduino_due_x/variant.h to 2 so Wire1 should be known.
What error message do you get if you compile the library with Wire1  ?

**Comment by RobTillaart** [comment]
@waspinator 
Is this issue solved now? if so how?

**Comment by waspinator** [comment]
It doesn't show any errors compiling, just doesn't seem to communicate with the device. The logic in your scanner doesn't detect any additional wire channels implemented in a Due. My modified version of your scanner does pick the DAC up though, but I haven't had a chance to try out your MCP4725 library again. I submitted a pull request to your scanner sketch to add Arduino Due support.

**Comment by RobTillaart** [comment]
Pull request #75 is merged
