### ISSUE TITLE
Read several sensors' data in same time

### ISSUE THREAD

**Issue by mhrahimi** [RobTillaart/Arduino#74]
I want to capture 6 DHT sensors' data in almost same time(less than 0.05sec tme diggrence).How could I do that?

**Comment by RobTillaart** [comment]
A DHT can be read in about 5-6 milli seconds , so you should be able to read 6 of them in sequence in 36 milliseconds = 0.036 seconds. 

A more practical problem might be that 6 sensors draw too much current, so you should use an external 5V powersource for the sensors. Keep all grounds Arduino and sensors connected so they all have the same reference.

regards,
Rob
