### ISSUE TITLE
AM2305/DHT44 does not work with Nodemcu and DHTstable 

### ISSUE THREAD

**Issue by sajjadesz** [RobTillaart/Arduino#77]
Hi. 
I already tested this library for arduino uno + AM2305/DHT44. It works perfectly but whenever I use this sketch for nodemcu with or with not pull-up resistor on pin 2, it does not work and get time out error. I,m using DHTstable library 0.2.0 version which  #said it,s the latest stable library for avr and arm.
Thanks!

**Comment by RobTillaart** [comment]
I do not have a nodemcu to test with. Is this a 3.3V device?

**Comment by mgulsoy** [comment]
Yes. That is a 3.3v device.

**Comment by RobTillaart** [comment]
You might need a bidirectional 3.3 - 5V convertor between the datalines?

**Comment by sajjadesz** [comment]
It works!!!!!!!!!Thanks a lot for your attention.
It works perfectly without any pull up resistor on pin 5 (D1 on NodeMcu development board)

**Comment by RobTillaart** [comment]
How did you make it work?
