### ISSUE TITLE
StopWatch not compiling with 'const' in function header.

### ISSUE THREAD

**Issue by Koepel** [RobTillaart/Arduino#78]
Using Arduino IDE 1.8.4, the compiler does not like the 'const' in the function header for "elapsed()", "isRunning()", "state()", "resolution()" in the file "Arduino/libraries/StopWatch/StopWatch.h"

I tried to remove those, and it did compile. I assume they are not really needed.

**Comment by RobTillaart** [comment]
I'm not using 1.8.4 yet but I'll remove const from the stopwatch class.
StopWatch 0.1.5 will be there asap

**Comment by RobTillaart** [comment]
Fixed in 0.1.5
