### ISSUE TITLE
No need to wait after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [RobTillaart/Arduino#79]
When the function Wire.requestFrom() returns, the I2C transaction has completely finished and the received data is waiting in a buffer in the Wire library. There is no need to wait for something to read those bytes from the buffer.

In the files:
"Arduino/libraries/hmc6532/examples/set2standby/set2standby.pde"
"Arduino/libraries/hmc6532/examples/set2continuous/set2continuous.pde"
"Arduino/libraries/hmc6532/examples/set2query/set2query.pde"
There is a `while(Wire.available() < 1);` after the Wire.requestFrom(). Those while-loops can be removed.

**Comment by RobTillaart** [comment]
Has been long since I touched that code (2011) so I did the following:
- replaced the while loop with a check on the received count, 
- updated the Wire.send/receive calls to post Arduino 1.00 era
- minor refactoring
Please let me know if you need fixes in this lib.
