### ISSUE TITLE
Make I2C sensor libraries ESP8266 friendly

### ISSUE THREAD

**Issue by beicnet** [RobTillaart/Arduino#86]
Hi Rob,

Focus on DHT12 and AM232X I2C libraries.

Please make your I2C sensor libraries ESP8266 friendly by adding like this for example:

This would go to the .h file:

```
// initialize AM232X for ESP8266 (ESP-01) which requires manual
// specification of sda and scl pins
#ifdef ESP8266
  void read(int sda, int scl);
#endif
```

and this to the .cpp file:

```
#ifdef ESP8266
 void AM232X::read(int sda, int scl) {
    Wire.begin(sda, scl);
 }
#endif
```
Kind regards,
Viktor

**Comment by RobTillaart** [comment]
DHT12 - fixed and tested
