### ISSUE TITLE
Compiler warning regarding architecture

### ISSUE THREAD

**Issue by ralfiii** [RobTillaart/Arduino#92]
When compiling a project with the DHT Lib in the ArduinoIDE with Arduino Uno selected, I get this warning:

WARNING: library DHT claims to run on (atmelavr) architecture(s) and may be incompatible with your current board which runs on (avr) architecture(s).

I'm new to this IDE, I suppose this needs to be addressed in the library.properties file changing the line to
architectures=avr,atmelavr

Cheers,
Ralf

**Comment by RobTillaart** [comment]
thx, low prio and if time permits I'll fix it.
Which of my DHT libs btw?

**Comment by ralfiii** [comment]
This code:
https://github.com/RobTillaart/Arduino/tree/master/libraries/DHTlib


2018-02-08 18:25 GMT+01:00 Rob Tillaart <notifications@github.com>:

**Comment by RobTillaart** [comment]
Fix is merged
